### ISSUE TITLE
Protection modules needing Updated

### ISSUE THREAD

**Issue by McyD** [MyEssentials/MyTown#53]
[MyTown][Prot]Module Mekanism failed to load. (ObsidianTNTBlastRadius)

[MyTown][Prot]Module ModularPowersuits failed to load. (net.machinemuse.utils.ModuleManager)

[MyTown][Prot]Module ThermalExpansion failed to load. (thermalexpansion.entity.EntityFlorb)

**Comment by odensc** [comment]
Was gonna submit a pull request to fix these, but they already are in the dev branch.

**Comment by McyD** [comment]
That was 2 months ago... I would say they are in need of updating again... as those mods have updated within the last month.

Ignore that, I looked at the old pull request and not the Dev branch.

**Comment by jgoett154** [comment]
All should be fixed in next version.

**Comment by raymondbh** [comment]
I still have this issue. 

14:50:51 [INFO] [MyTown][Prot]Module ThermalExpansion failed to load. (thermalexpansion.entity.EntityFlorb)
14:50:51 [INFO] [MyTown][Prot]Module ModularPowersuits failed to load. (net.machinemuse.utils.ModuleManager)

Running MyTown-1.6.1.16.jar and
ThermalExpansion-3.0.0.7.jar
ModularPowersuits-1.6.4-0.10.0-118.jar
